#!/usr/bin/env python3
"""`just new-equity-instrument SYMBOL`: writes config/instruments/<symbol>.toml for one US stock.

Same shape as config/instruments/spy.toml (tick 0.01, whole shares, regular NYSE hours and the
NYSE holiday calendar), with the next unused instrument id. Its `limits` points at
config/limits/spy.toml itself rather than a copy, so the new instrument can never carry looser
caps than SPY's ($25 per order, $50 per day, $5 daily loss): there is one limits file to tighten,
and `scripts/ops/preflight.py` still checks it against the canary caps before any live start.

Refuses (exit 1) on a malformed symbol or when the file already exists. Standard library only.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
# Uppercase letters with an optional class suffix (BRK.B), at most 6 characters.
SYMBOL_RE = re.compile(r"^(?=.{1,6}$)[A-Z]+(\.[A-Z]+)?$")

TEMPLATE = """\
# {symbol}: generated by `just new-equity-instrument {symbol}` from spy.toml's shape.
# Protected zone: human approval required (root CLAUDE.md rule 3); tighten-only (rule 4).

id = {id}
symbol = "{symbol}"
tick_size = "0.01"      # US equities trade in cent increments
qty_step = "1"          # whole shares only
min_qty = "1"
allows_fractional = false
# SPY's limits file itself, not a copy: one set of caps for every canary stock.
limits = "../limits/spy.toml"

[trading_hours]
tz = "America/New_York"
open = "09:30"
close = "16:00"
days = ["Mon", "Tue", "Wed", "Thu", "Fri"]
calendar = "calendars/nyse.toml"
"""


def validate_symbol(symbol: str) -> str:
    if not SYMBOL_RE.fullmatch(symbol):
        raise ValueError(
            f"invalid symbol {symbol!r}: use 1-6 uppercase letters, optionally with a dot "
            "class suffix (e.g. F, XYZ, BRK.B)"
        )
    return symbol


def instrument_path(symbol: str, config_dir: Path) -> Path:
    return config_dir / "instruments" / f"{symbol.lower()}.toml"


def next_id(instruments_dir: Path) -> int:
    ids = [tomllib.loads(p.read_text())["id"] for p in instruments_dir.glob("*.toml")]
    return max(ids, default=1) + 1


def write_instrument(symbol: str, config_dir: Path) -> Path:
    symbol = validate_symbol(symbol)
    path = instrument_path(symbol, config_dir)
    if path.exists():
        raise FileExistsError(f"{path} already exists; not overwriting it")
    if not (config_dir / "limits" / "spy.toml").is_file():
        raise FileNotFoundError(f"{config_dir / 'limits/spy.toml'} is missing")
    path.write_text(TEMPLATE.format(symbol=symbol, id=next_id(path.parent)))
    return path


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("symbol")
    p.add_argument("--config-dir", type=Path, default=ROOT / "config")
    args = p.parse_args(argv)
    try:
        path = write_instrument(args.symbol, args.config_dir)
    except (ValueError, FileExistsError, FileNotFoundError) as exc:
        print(f"new-equity-instrument: {exc}", file=sys.stderr)
        return 1
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
