"""Writes sample_day.csv: a synthetic, deterministic L2 recording in the
qc-gateway record format (see engine/crates/gateway/src/record.rs).

Run from this directory: python3 generate_sample_day.py
The output is committed; regenerate only on purpose and update the expected hash.
"""

import random

TICK_PRICE_DIGITS = 1  # prices are integer ticks of 0.1
QTY_UNIT = 10_000  # quantities are integer units of 0.0001
LEVELS = 5
RECORDS = 5000
GAP_AT = 2500  # one delta is dropped here, then a snapshot resyncs
START_NS = 1_767_571_200 * 1_000_000_000  # 2026-01-05T00:00:00Z


def price(ticks: int) -> str:
    return f"{ticks // 10}.{ticks % 10}"


def qty(units: int) -> str:
    return f"{units // QTY_UNIT}.{units % QTY_UNIT:04d}"


def main() -> None:
    rng = random.Random(20260105)
    best_bid = 650_000
    bids = {best_bid - i: rng.randint(40, 5000) for i in range(LEVELS)}
    asks = {best_bid + 1 + i: rng.randint(40, 5000) for i in range(LEVELS)}
    seq = 1000
    ts_ex = START_NS
    ts_local = START_NS
    out = ["# synthetic sample day; generated by generate_sample_day.py (seed 20260105)"]

    def stamp() -> str:
        return f"{ts_ex},{ts_local}"

    def snapshot() -> str:
        b = ";".join(f"{price(p)}@{qty(q)}" for p, q in sorted(bids.items(), reverse=True))
        a = ";".join(f"{price(p)}@{qty(q)}" for p, q in sorted(asks.items()))
        return f"S,1,{seq},{stamp()},{b},{a}"

    def delta(side: str, p: int, q: int, emit: bool = True) -> None:
        nonlocal seq
        seq += 1
        book = bids if side == "B" else asks
        if q == 0:
            book.pop(p, None)
        else:
            book[p] = q
        if emit:
            out.append(f"D,1,{seq},{side},{price(p)},{qty(q)},{stamp()}")

    out.append(snapshot())
    gap_open = False
    resynced = False
    while len(out) < RECORDS:
        ts_ex += rng.randint(20, 400) * 1_000_000
        if rng.random() < 0.01:
            ts_ex += 1_500_000_000  # a quiet spell longer than the stale-data limit
        ts_local = max(ts_local + 1, ts_ex + rng.randint(200_000, 900_000))
        roll = rng.random()
        if len(out) >= GAP_AT and not gap_open and not resynced and roll < 0.5:
            gap_open = True
            p = max(bids)
            delta("B", p, bids[p] + 100, emit=False)  # lost on the wire
            continue
        if gap_open and len(out) >= GAP_AT + 20:
            gap_open, resynced = False, True
            out.append(snapshot())
            continue
        if roll < 0.5:
            side = rng.choice("BS")
            book = bids if side == "B" else asks
            p = rng.choice(sorted(book))
            delta(side, p, rng.randint(40, 5000))
        elif roll < 0.8:
            aggressor = rng.choice("BS")
            book = asks if aggressor == "B" else bids
            p = min(book) if aggressor == "B" else max(book)
            size = rng.randint(5, min(40, book[p] - 10)) if book[p] > 15 else 0
            if size:
                out.append(f"T,1,{aggressor},{price(p)},{qty(size)},{stamp()}")
                delta("S" if aggressor == "B" else "B", p, book[p] - size)
        else:
            up = rng.random() < 0.5
            if up:
                delta("S", min(asks), 0)
                delta("S", max(asks) + 1, rng.randint(40, 5000))
                delta("B", max(bids) + 1, rng.randint(40, 5000))
                delta("B", min(bids), 0)
            else:
                delta("B", max(bids), 0)
                delta("B", min(bids) - 1, rng.randint(40, 5000))
                delta("S", min(asks) - 1, rng.randint(40, 5000))
                delta("S", max(asks), 0)
        assert max(bids) < min(asks), "generator produced a crossed book"
    with open("sample_day.csv", "w", encoding="ascii") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
